### ISSUE TITLE
Überarbeitung der Funktionalen Anforderungen

### ISSUE THREAD

**Issue by Nydery** [steinmax/Aduno#27]
# Task
Rethink the project concept, especially the functional requirements(Pflichtenheft).

**Comment by Nydery** [comment]
# State
**Done**: New and improved functional requirements and use cases can be found [here](https://github.com/steinmax/reSign/blob/main/Projektmanagement/Pflichtenheft_20.12.2021.pdf) (official document) and [here](https://github.com/steinmax/reSign/tree/main/Projektmanagement/Brainstorm) (Brainstorm and internal documents).
## Remaining (unclear) topics
- List of absent/present pupils: How does the teacher get to it?
- Anmeldung via schoolaccounts: HTL OAuth is down? How does it actually work (programmatically)?
- Intervals for REST requests. Current lesson, room occupancy (count of pupils present), ...

**Comment by Nydery** [comment]
# Edit
Maybe it is better to use Sockets after all, because otherwise we're not able to have a two-way-connection.
So for example: Custom messages (set via the Terminal Software) would be impossible or not instantly displayed.

**Comment by benjaminImsirovic** [comment]
Done: Use Cases + Use Case Diagram have been revised, 
[Pflichtenheft.pdf](https://github.com/steinmax/reSign/files/7837352/Pflichtenheft.pdf)
new and improved functional requirements. (Pflichtenheft) is now done.
